name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.3"

    - uses: leafo/gh-actions-luarocks@v4

    - name: setup
      run: |
        luarocks install busted

    - name: test
      run: |
        busted -C ./test/Modules/audiochecklist/ -o TAP -p ".*%.lua" ./